### ISSUE TITLE
3D Printing settings

### ISSUE THREAD

**Issue by JGrzybowski** [Bastardkb/Scylla#1]
Thanks for sharing 3D files for Scylla I wanted to build one for a long time using amoebas.

Are there any recommended settings regarding printing?
Like: 
- infill %
- layer height
- support type
- printing material (I saw PLA in the store but do you know how others do)

**Comment by bstiq** [comment]
Hello,

Glad to know you're building a Scylla !

On the Github there's a *Print the case *section, with a link to the
documentation on the exact print settings and filaments.

Regards,

*Quentin LEBASTARD*


Le jeu. 23 sept. 2021 à 16:51, Jan Grzybowski ***@***.***> a
écrit :
